language: python
python:
  - 3.7
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.ccache  # https://github.com/travis-ci/travis-ci/issues/5853

env:
  global:
    # Doctr deploy key for rwijtvliet/polygonation
    - secure: "Fk5lS2rDy34XJiKFjsWIXia/K9Xe1Qg3dxDJ+Lq1c2jVfrsOCLEYq5ySWCB9KqZb8vtRd5HRDtmAbTKfshT+eusCSgeKi14bnLKLWPJITROznKUzosoxFwIaT5yXi74DlwxP05YBg1O16NIdoz3sU/e67dOaicJ5Ty6O8fH4AlVQTArc05+fgSZR1WIT+g08WXCt3IudYTXEqWuBxJBzt75fTajPr1skaAk0aieAD3EIoLcs/2VgtNITUd25qN7BaZA3yF3BJ39VJr9mZvONfxFgJkNJ5XJ5xyz2p+KlfhkKFFPfLVuN+bq8KcGsd5O9OIEXq1sQEaJbgqzwwrQMeTO2EsCNrU7tKhrBaCPQGLp/nyk86+Vvy6BpswRzv/adETwcXelkmEJ+jA8BMnWQuB+RmUa05j2K2z3Stl22ZAXGibePhIPBdiWag1ldNCB81NPbHZUflKWz3v9Owt21ffHre0m3xAovUmLd9vI0n/TemPjXt7gmVEFJ0Ymc4tDmC8X9HMu+MiN1qZVzImnKEJHROOOiFM+DdaE6eScT+POCw38xKc1u7677pad+3kO+nSrorguR0PSUeTvv/k+AzaOzsemQ+2mHlF08+Nxl1a9k/SCuvtRwpkDdmoEBaVVav38wIWDiR0v4oUWPYR4T1CGALj/+FgG3byt0xynMP0g="

install:
  # The versions of pip and numpy that come pre-installed are often too old and
  # can cause problems. Upgrade them.
  - pip install --upgrade pip numpy
  # Install this package and the packages listed in requirements.txt.
  - pip install .
  # Install extra requirements for running tests and building docs.
  - pip install -r requirements-dev.txt

script:
  - coverage run -m pytest  # Run the tests and check for test coverage.
  - coverage report -m  # Generate test coverage report.
  - codecov  # Upload the report to codecov.
  - flake8  # Enforce code style ('relaxed' line length limit is set in .flake8 config file).
  - make -C docs html  # Build the documentation.
